ConnectEverything/nats-by-example

examples/messaging/request-reply/rust/main.rs

Signed-off-by: Jarema <tomasz@nats.io>

Add request/reply Rust example

---

docker/rust/Cargo.toml
examples/messaging/json/rust/main.rs
examples/messaging/json/rust/output.cast
examples/messaging/json/rust/output.txt
html/examples/messaging/index.html
html/examples/messaging/json/index.html
html/examples/messaging/json/rust/index.html
html/examples/messaging/json/rust/output.cast
html/index.html

@Jarema derived from your example in Slack :wink:

Add Rust json example

---

cmd/nbe/tmpl/index.html

Signed-off-by: Byron Ruth <byron@nats.io>

Add video link to homepage

---

.github/workflows/ci.yaml

Signed-off-by: Jarema <tomasz@nats.io>

Use docker layers caching

---

docker/rust/Dockerfile
examples/kv/intro/rust/main.rs

Signed-off-by: Jarema <tomasz@nats.io>

Add Rust kv example

---

cmd/nbe/main_test.go

Hi, thanks for making NATS by examples project. 😄 I'm going through this example to learn NATS!
I found the nbe's `parseReader` has compile error, so I fix it. 😉

Fix TestParseReader compile error

---

examples/jetstream/workqueue-stream/java/Main.java

@scottf My attempt to mimic the Go workqueue stream example.

Add jetstream/workqueue-stream/java example

---

docker/rust/Dockerfile
examples/jetstream/interest-stream/rust/main.rs
examples/jetstream/limits-stream/rust/main.rs
examples/jetstream/workqueue-stream/rust/main.rs

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

Add Rust example for interest based stream

---

cmd/nbe/go.mod

Updating CLI module name

---

examples/messaging/request-reply/elixir/main.exs
examples/messaging/request-reply/meta.yaml

Added a request/reply sample for Elixir

Adding elixir sample for request-reply

---

examples/jetstream/ack-ack/dotnet2/Main.cs
examples/jetstream/ack-ack/dotnet2/jetstream-ack-ack.csproj
examples/jetstream/ack-ack/java/Main.java

https://github.com/ConnectEverything/nats-by-example/issues/211

[DotNet2] AckAck Example

---

examples/jetstream/ack-ack/dotnet2/Main.cs
examples/jetstream/list-subjects/dotnet2/Main.cs
examples/jetstream/list-subjects/dotnet2/list-subjects.csproj

https://github.com/ConnectEverything/nats-by-example/issues/217

[C# DotNet2] List Subjects

---

examples/jetstream/ack-ack/go/main.go

https://github.com/ConnectEverything/nats-by-example/issues/207

[GO] Ack Ack

---

examples/messaging/iterating-multiple-subscriptions/java/Main.java

Resolves https://github.com/ConnectEverything/nats-by-example/issues/245
Replaces PR from fork: https://github.com/ConnectEverything/nats-by-example/pull/246

[Java] Iterating Over Multiple Subscriptions

---

docker/java/build.gradle
examples/messaging/json/java/Main.java

Resolves https://github.com/ConnectEverything/nats-by-example/issues/243
Replaces PR from fork: https://github.com/ConnectEverything/nats-by-example/pull/244

[Java] JSON for Message Payloads

---

examples/jetstream/ack-ack/go/main.go
examples/jetstream/limits-stream/go/main.go
examples/jetstream/limits-stream/java/Main.java
examples/jetstream/limits-stream/rust/main.rs
examples/jetstream/list-subjects/go/main.go

Resolves https://github.com/ConnectEverything/nats-by-example/issues/249
Replaces PR from fork: https://github.com/ConnectEverything/nats-by-example/pull/250

[Java] Limits-based Stream

---

examples/jetstream/interest-stream/dotnet2/Main.cs
examples/jetstream/interest-stream/go/main.go
examples/jetstream/interest-stream/java/Main.java

Resolves https://github.com/ConnectEverything/nats-by-example/issues/251
Replaces PR from fork: https://github.com/ConnectEverything/nats-by-example/pull/252

[Java] Interest-based Stream

---

examples/messaging/concurrent/java/Main.java

Resolves https://github.com/ConnectEverything/nats-by-example/issues/247
Replaces PR from fork: https://github.com/ConnectEverything/nats-by-example/pull/248

[Java] Concurrent Message Processing

---

examples/jetstream/pull-consumer/java/Main.java

Resolves https://github.com/ConnectEverything/nats-by-example/issues/258

[Java] Pull Consumers

---

examples/jetstream/push-consumer/go/main.go
examples/jetstream/push-consumer/java/Main.java
examples/jetstream/queue-push-consumer/go/main.go

Resolves https://github.com/ConnectEverything/nats-by-example/issues/260

[Java] Push Consumers (legacy)
